travis:
  secure:
    BINSTAR_TOKEN: bCwUrgq6/XD+KnP9OMecGUzmN4j7O5MzNuDxtA0xi+KEdwCL4bCTQyvahqNIH+aYbCDrhSq1/SwMfQ9sssUDLHpjaP3ZodjZFAzu96PqEWeJk9HUMfSyRnq5wdMe1N3Rfj7uXjzkk7Otwu2iAetHO8uhOkQexiAsDSdumcQa4x3KraRe999tAiPlR3NODASqdzkYykhMJxocMdJCrwOz8mcMD7wycjqK2GjlMGhbDS2Z2glWV1k1O5l/1+HFr8JM4txpY2HKzWS28Ou6M9xH8DOj8tSfgH/ttklltt1Itg+NjGU/iiq3YOJUJWv05pd7ubOb052RL1dDpTg2iqbp2OQRQwcuzfga3iX77Xv7GSHRT/rVBNWQ2JHG6EpOje7svBbcCALoJva4nlC/u8WDRND5LVXYG+X60d7OeB1/4rQgBKaWErxTrRN5KLnyzVei+rpFZ0daQdHiw9x7Rj/LvL+rt0W8W1HUEqdUqCWATtogNkFgB0f6tr4mSv4nNQvKpzfY3RL3o2BifPhJtFslV0+FfoYmi6GDysbFHDnWQITi3Rt8oNNuo6dLcIJLfzS7wMKF3B0ZDx2xLK1Kk3rcrLA/oJDlrOumZkZBIHA2N7SYlXfJLz2TJUFhfCY3EP4TPvILovwWBws0TPEWKxVSr0Natpvn+F9z3TGdcJ7ocoo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
